
/*All User's are stored in APP_USER table*/
 create table APP_USER (
        id integer generated by default as identity (start with 1),
        EMAIL varchar(255) not null,
        FIRST_NAME varchar(255) not null,
        LAST_NAME varchar(255) not null,
        PASSWORD varchar(255) not null,
        SSO_ID varchar(255) not null,
        STATE varchar(255) not null,
        primary key (id)
    );
  
/* JOIN TABLE for MANY-TO-MANY relationship*/ 
create table APP_USER_USER_PROFILE (
        USER_ID integer not null,
        USER_PROFILE_ID integer not null,
        primary key (USER_ID, USER_PROFILE_ID)
    );

create table DC_PRIVILEGE (
        DC_ID bigint not null,
        PRIVILEGE_ID bigint not null,
        primary key (DC_ID, PRIVILEGE_ID)
    );

create table DC_PRIVILEGE_AUD (
        REV integer not null,
        DC_ID bigint not null,
        PRIVILEGE_ID bigint not null,
        REVTYPE tinyint,
        primary key (REV, DC_ID, PRIVILEGE_ID)
    );
	
create table DEVELOPMENTCENTER (
        DC_ID bigint not null,
        DELETEFLAG boolean,
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        NAME varchar(255),
        primary key (DC_ID)
    );

create table DEVELOPMENTCENTER_AUD (
        DC_ID bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        DELETEFLAG boolean,
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        NAME varchar(255),
        primary key (DC_ID, REV)
    );

create table EMPLOYEE (
        EMPLOYEE_ID bigint not null,
        APPAREA varchar(255),
        BADGEENDDATE date,
        CUBICLEID varchar(255),
        DELETEFLAG boolean,
        DSID varchar(255),
        EMAIL varchar(255),
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        MANAGERID boolean,
        NAME varchar(100) not null,
        REQUESTTYPE boolean,
        primary key (EMPLOYEE_ID)
    );

create table EMPLOYEE_AUD (
        EMPLOYEE_ID bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        APPAREA varchar(255),
        BADGEENDDATE date,
        CUBICLEID varchar(255),
        DELETEFLAG boolean,
        DSID varchar(255),
        EMAIL varchar(255),
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        MANAGERID boolean,
        NAME varchar(100),
        REQUESTTYPE boolean,
        primary key (EMPLOYEE_ID, REV)
    );

	create table EMPLOYEE_DC (
        EMPLOYEE_DC_ID bigint not null,
        DC_ID boolean,
        DELETEFLAG boolean,
        EMPLOYEE_ID boolean,
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        primary key (EMPLOYEE_DC_ID)
    );
	
	create table EMPLOYEE_DC_AUD (
        EMPLOYEE_DC_ID bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        DC_ID boolean,
        DELETEFLAG boolean,
        EMPLOYEE_ID boolean,
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        primary key (EMPLOYEE_DC_ID, REV)
    );
	
	create table EMPLOYEE_DC_PRIVILEGE (
        EMPLOYEE_DC_ID bigint not null,
        PRIVILEGE_ID bigint not null
    );
	
	create table EMPLOYEE_DC_PRIVILEGE_AUD (
        REV integer not null,
        EMPLOYEE_DC_ID bigint not null,
        PRIVILEGE_ID bigint not null,
        REVTYPE tinyint,
        primary key (REV, EMPLOYEE_DC_ID, PRIVILEGE_ID)
    );
	
	create table PRIVILEGE (
        PRIVILEGE_ID bigint not null,
        DELETEFLAG boolean,
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        NAME varchar(255),
        primary key (PRIVILEGE_ID)
    );
	
	create table PRIVILEGE_AUD (
        PRIVILEGE_ID bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        DELETEFLAG boolean,
        LASTMODIFIED date,
        LASTMODIFIEDBY varchar(255),
        NAME varchar(255),
        primary key (PRIVILEGE_ID, REV)
    );
	
	create table REVINFO (
        REV integer generated by default as identity (start with 1),
        REVTSTMP bigint,
        primary key (REV)
    );
	
	create table USER_PROFILE (
        id integer generated by default as identity (start with 1),
        TYPE varchar(15) not null,
        primary key (id)
    );
	
	alter table APP_USER 
        add constraint UK_hqk6uc88j3imq8u9jhro36vt3  unique (SSO_ID);
		
	alter table DC_PRIVILEGE 
        add constraint UK_t9p3sxmj5r5xng3ulblhy49xi  unique (PRIVILEGE_ID);
		
	alter table EMPLOYEE_DC_PRIVILEGE 
        add constraint UK_8lp1gps9lltr01840d8vyw7wn  unique (PRIVILEGE_ID)

    alter table USER_PROFILE 
        add constraint UK_cva7m2blp7ekclxworqxau1l7  unique (TYPE);
		
    alter table APP_USER_USER_PROFILE 
        add constraint FK_gs2lq4vmukguubh36utd4r2cl 
        foreign key (USER_PROFILE_ID) 
        references USER_PROFILE;

    alter table APP_USER_USER_PROFILE 
        add constraint FK_brmce0t584euix4wb4rursf1q 
        foreign key (USER_ID) 
        references APP_USER;

    alter table DC_PRIVILEGE 
        add constraint FK_t9p3sxmj5r5xng3ulblhy49xi 
        foreign key (PRIVILEGE_ID) 
        references PRIVILEGE;

    alter table DC_PRIVILEGE 
        add constraint FK_r64ehqy9q812i02tpiyoh8ojl 
        foreign key (DC_ID) 
        references DEVELOPMENTCENTER;

    alter table DC_PRIVILEGE_AUD 
        add constraint FK_d1na094qwnykdnv1xpe2tnowb 
        foreign key (REV) 
        references REVINFO;

    alter table DEVELOPMENTCENTER_AUD 
        add constraint FK_7h5j76u096b6jj1s38i8dfyd6 
        foreign key (REV) 
        references REVINFO;
 
    alter table EMPLOYEE_AUD 
        add constraint FK_t6ybx1sbutm2dmawkw79u05mu 
        foreign key (REV) 
        references REVINFO;

    alter table EMPLOYEE_DC_AUD 
        add constraint FK_r11le6yf1q439rtvwcxn8ypas 
        foreign key (REV) 
        references REVINFO;

    alter table EMPLOYEE_DC_PRIVILEGE 
        add constraint FK_8lp1gps9lltr01840d8vyw7wn 
        foreign key (PRIVILEGE_ID) 
        references PRIVILEGE;

    alter table EMPLOYEE_DC_PRIVILEGE 
        add constraint FK_icjeiwq90sc9t5m96s1msd180 
        foreign key (EMPLOYEE_DC_ID) 
        references EMPLOYEE_DC;

    alter table EMPLOYEE_DC_PRIVILEGE_AUD 
        add constraint FK_eyon6gi32jfpbd07vmf7ngg3o 
        foreign key (REV) 
        references REVINFO;
 
    alter table PRIVILEGE_AUD 
        add constraint FK_20w4q54dnhl9ybkvwog138moh 
        foreign key (REV) 
        references REVINFO;

    create sequence DC_SEQ start with 1; 
    create sequence EMPLOYEE_DC_SEQ start with 1;
    create sequence PRIVILEGE_SEQ start with 1;